export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const FETCH_LOGGED_USER_REQUEST = "FETCH_LOGGED_USER_REQUEST";
export const FETCH_LOGGED_USER_SUCCESS = "FETCH_LOGGED_USER_SUCCESS";
export const FETCH_LOGGED_USER_FAILURE = "FETCH_LOGGED_USER_FAILURE";

export const REGISTER_BUSINESS_USER = "REGISTER_BUSINESS_USER";
export const REGISTER_CLIENT_USER = "REGISTER_CLIENT_USER";

export const USER_LOGGEDIN = "USER_LOGGEDIN";

export const CURRENT_USER_DETAILS = "CURRENT_USER_DETAILS";
export const CURRENT_CLIENT_DETAILS = "CURRENT_CLIENT_DETAILS";
export const STORE_TRADING_STATUS = "STORE_TRADING_STATUS";

export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
