export const SHOW_PASSWORD = "SHOW_PASSWORD";
export const SET_LOADING = "SET_LOADING";
export const SET_ACTIVE_STEP = "SET_ACTIVE_STEP";
export const SET_LOGGEDIN_STATUS = "SET_LOGGEDIN_STATUS";
export const SET_MODAL = "SET_MODAL";
export const SET_UPDATE_MODAL = "SET_UPDATE_MODAL";
